name: Automated Tests
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer
          coverage: pcov
          extensions: mbstring, xml, ctype, iconv, intl, mysql

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup forumify
        run: |
          cd tests
          composer install --no-progress --prefer-dist --optimize-autoloader
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
          php bin/console forumify:platform:setting -k forumify.platform_installed --value true
          php bin/console forumify:plugins:refresh --env=test
          php bin/console forumify:plugins:activate forumify/forumify-remove-branding-plugin --env=test

      - name: Run tests
        run: cd tests && vendor/bin/phpunit
